version: '2.1'

services:
  mysql_database:
    restart: always
    container_name: "mysql_database"
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: "example"
    image: "mysql:latest"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"-uroot", "-ppass", "ping", "-h", "127.0.0.1"]
      timeout: 20s
      retries: 10

  mock:
    restart: always
    build: mock
    container_name: "mock"
    volumes:
      - /Users/albatros/PycharmProjects/Atom-QA-Python/Final_Project/mock:/mock
    ports:
      - "5000:5000"
    links:
      - "mysql_database:mysql_database"
    depends_on:
      mysql_database:
        condition: service_healthy

  app:
    restart: always
    image: "myapp"
    container_name: "myapp"
    ports:
      - "5555:5555"
    volumes:
      - /Users/albatros/PycharmProjects/Atom-QA-Python/Final_Project/path:/config
    links:
      - "mysql_database:mysql_database"
      - "mock:mock"
    command: "/app/myapp --config=/config/config.conf"
    depends_on:
      mysql_database:
        condition: service_healthy
